//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace urban_archive.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArchiveCertificate
    {
        public string projectName { get; set; }
        public string location { get; set; }
        public string developmentOrganization { get; set; }
        public Nullable<System.DateTime> dateArchive { get; set; }
        public string projectStartDate { get; set; }
        public string projectFinishDate { get; set; }
        public string submitPerson { get; set; }
        public string telphoneSubmitPerson { get; set; }
        public string recipient { get; set; }
        public string archiveCertificateNo { get; set; }
        public Nullable<long> projectID { get; set; }
        public Nullable<System.DateTime> datebianhao { get; set; }
    }
}
