//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace urban_archive.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookBorrowInfo
    {
        public int ID { get; set; }
        public Nullable<int> bookNo { get; set; }
        public string borrower { get; set; }
        public Nullable<System.DateTime> borrowDate { get; set; }
        public Nullable<System.DateTime> returnDate { get; set; }
    }
}
