//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace urban_archive.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectInfo
    {
        public long projectID { get; set; }
        public string projectName { get; set; }
        public string developmentOrganization { get; set; }
        public string devolonpentOrgContacter { get; set; }
        public string mobilephoneNoDevelopment { get; set; }
        public string telphoneNoDevelopment { get; set; }
        public string constructionOrganization { get; set; }
        public string constructionOrgContacter { get; set; }
        public string mobilephoneNoConstruction { get; set; }
        public string telphoneNoConstruction { get; set; }
        public string disignOrganization { get; set; }
        public string designOrgaContacter { get; set; }
        public string telphoneNoDesignOrga { get; set; }
        public string mobilephoneNoDesignOrga { get; set; }
        public string jianliUnit { get; set; }
        public string jianliUnitContacter { get; set; }
        public string telphoneNoJianliUnit { get; set; }
        public string mobilephoneNoJianliUnit { get; set; }
        public string location { get; set; }
        public string securityID { get; set; }
        public string retentionPeriodNo { get; set; }
        public string contractNo { get; set; }
        public string status { get; set; }
        public string storagePath { get; set; }
        public string archivesCode { get; set; }
        public string latitudeL { get; set; }
        public string latitudeR { get; set; }
        public string longitudeL { get; set; }
        public string longitudeR { get; set; }
        public Nullable<long> textMaterial { get; set; }
        public Nullable<long> drawing { get; set; }
        public Nullable<bool> isLingquYijiaoshu { get; set; }
        public Nullable<bool> isFafangHegezheng { get; set; }
        public Nullable<bool> isCharge { get; set; }
        public Nullable<bool> isAcceptYanshou { get; set; }
        public string memo { get; set; }
        public string structureTypeID { get; set; }
        public string newLocation { get; set; }
        public string seqNo { get; set; }
        public Nullable<bool> isFinanceCharge { get; set; }
        public Nullable<bool> isYD { get; set; }
        public int id { get; set; }
        public string mappipei { get; set; }
        public Nullable<long> GCId { get; set; }
        public Nullable<int> Dwgclx { get; set; }
        public string TelConstruction { get; set; }
        public string TelDisign { get; set; }
        public string TelJianli { get; set; }
        public string Kcdw { get; set; }
        public string Kcdwlxr { get; set; }
        public string Kcdwlxdh { get; set; }
        public string Djdw { get; set; }
        public string Ydghxkzh { get; set; }
        public string Ghxkzh { get; set; }
        public string Lxpzwh { get; set; }
        public string Sgxkzh { get; set; }
        public Nullable<int> Jclx { get; set; }
        public Nullable<double> Ydmj { get; set; }
        public Nullable<int> Jglx { get; set; }
        public Nullable<int> Zs { get; set; }
        public Nullable<double> Gcys { get; set; }
        public Nullable<double> Gcjs { get; set; }
        public string Guid { get; set; }
        public string ArchivesId { get; set; }
        public Nullable<long> ConsUnitId { get; set; }
        public string Lrr { get; set; }
        public Nullable<System.DateTime> fazhaoTime { get; set; }
        public string Zlr { get; set; }
        public Nullable<System.DateTime> Zlrq { get; set; }
    }
}
