//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace urban_archive.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_gxarchiveMainList
    {
        public long paperProjectSeqNo { get; set; }
        public Nullable<int> volNo { get; set; }
        public string archivesNo { get; set; }
        public string paijiaNo { get; set; }
        public string archivesTitle { get; set; }
        public string licenseNo { get; set; }
        public string developmentOrganization { get; set; }
        public string constructionOrganization { get; set; }
        public Nullable<System.DateTime> jgDate { get; set; }
        public string remarks { get; set; }
        public string changeLog { get; set; }
        public string location { get; set; }
        public string registrationNo { get; set; }
        public string isNB { get; set; }
    }
}
