//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace urban_archive.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_gxreceiveArchiveDetail
    {
        public Nullable<long> projectNo { get; set; }
        public string projectName { get; set; }
        public string developmentOrganization { get; set; }
        public string constructionOrganization { get; set; }
        public string mobilephoneNoDevelopment { get; set; }
        public string mobilephoneNoConstruction { get; set; }
        public string submitPerson { get; set; }
        public string recipient { get; set; }
        public Nullable<System.DateTime> dateReceived { get; set; }
        public string collator { get; set; }
        public Nullable<System.DateTime> lqDate { get; set; }
        public Nullable<System.DateTime> dateArchive { get; set; }
        public long paperProjectSeqNo { get; set; }
    }
}
