//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace urban_archive.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_projectList
    {
        public string constructionOrganization { get; set; }
        public string projectName { get; set; }
        public string developmentOrganization { get; set; }
        public string status { get; set; }
        public long paperProjectSeqNo { get; set; }
        public string startArchiveNo { get; set; }
        public string endArchiveNo { get; set; }
        public Nullable<System.DateTime> lqDate { get; set; }
        public string submitPerson { get; set; }
        public string recipient { get; set; }
        public Nullable<System.DateTime> dateReceived { get; set; }
        public string collator { get; set; }
        public Nullable<System.DateTime> dateArchive { get; set; }
        public long projectID { get; set; }
        public string statusName { get; set; }
        public string location { get; set; }
        public string startPaijiaNo { get; set; }
        public string endPaijiaNo { get; set; }
        public string startRegisNo { get; set; }
        public string endRegisNo { get; set; }
        public Nullable<long> projectNo { get; set; }
        public Nullable<long> character2cm { get; set; }
        public Nullable<long> character3cm { get; set; }
        public Nullable<long> character4cm { get; set; }
        public Nullable<long> drawing2cm { get; set; }
        public Nullable<long> drawing3cm { get; set; }
        public Nullable<long> drawing4cm { get; set; }
        public Nullable<long> drawing5cm { get; set; }
        public Nullable<long> drawingVolumeCount { get; set; }
        public Nullable<long> character5cm { get; set; }
        public Nullable<long> characterVolumeCount { get; set; }
        public string InchCountDetail { get; set; }
        public Nullable<long> originalInchCount { get; set; }
        public string archivesCount { get; set; }
        public string disignOrganization { get; set; }
        public string licenseNo { get; set; }
        public string licenseDate { get; set; }
        public string projectStartDate { get; set; }
        public string projectFinishDate { get; set; }
        public string luruTime { get; set; }
        public Nullable<System.DateTime> jgDate { get; set; }
        public Nullable<long> textMaterial { get; set; }
        public Nullable<long> drawing { get; set; }
        public Nullable<long> PhotoCount { get; set; }
        public string transferUnit { get; set; }
        public string telphoneSubmitPerson { get; set; }
        public string archiveCertificateNo { get; set; }
        public string shizhengNoStart { get; set; }
        public string shizhengNoEnd { get; set; }
        public string newLocation { get; set; }
        public string qjdyYear { get; set; }
        public string qjdyNo { get; set; }
        public string mainCategoryID { get; set; }
        public string csyj { get; set; }
        public string csyjPerson { get; set; }
        public Nullable<System.DateTime> csyjDate { get; set; }
        public Nullable<long> originalVolumeCount { get; set; }
        public Nullable<decimal> originalMoneyAmount { get; set; }
        public Nullable<long> copyInchCount { get; set; }
        public Nullable<decimal> copyMoneyCount { get; set; }
        public Nullable<decimal> totalMoney { get; set; }
        public string prevClassNo { get; set; }
        public string paijiaRange { get; set; }
        public Nullable<System.DateTime> bianhaoTime { get; set; }
        public string securityID { get; set; }
        public string structureTypeID { get; set; }
        public string overground { get; set; }
        public string underground { get; set; }
        public Nullable<double> height { get; set; }
        public Nullable<double> buildingArea { get; set; }
        public string changeLog { get; set; }
        public Nullable<System.DateTime> lqyjsDate { get; set; }
        public string lqperson { get; set; }
        public string subDictionaryID { get; set; }
        public string minorDictionaryID { get; set; }
        public string fzryj { get; set; }
        public string fzryjPerson { get; set; }
        public Nullable<System.DateTime> fzryjDate { get; set; }
        public string zgyj { get; set; }
        public string zgyjPerson { get; set; }
        public Nullable<System.DateTime> zgyjDate { get; set; }
        public string collationRequirement { get; set; }
        public string firstResponsible { get; set; }
        public string responsibleOther { get; set; }
        public string memo { get; set; }
        public Nullable<long> character1cm { get; set; }
        public Nullable<long> drawing1cm { get; set; }
        public string jianliUnit { get; set; }
        public string coordinate { get; set; }
        public string mappipei { get; set; }
        public string storagePath { get; set; }
    }
}
