//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace urban_archive.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_transferStatis
    {
        public Nullable<long> projectNo { get; set; }
        public long paperProjectSeqNo { get; set; }
        public string startArchiveNo { get; set; }
        public string endArchiveNo { get; set; }
        public string developmentOrganization { get; set; }
        public string projectName { get; set; }
        public string recipient { get; set; }
        public string collator { get; set; }
        public string archivesCount { get; set; }
        public Nullable<System.DateTime> dateArchive { get; set; }
        public string archiveCertificateNo { get; set; }
        public Nullable<System.DateTime> typerDate { get; set; }
        public Nullable<long> originalInchCount { get; set; }
        public Nullable<long> characterThickness { get; set; }
        public Nullable<long> drawingThickness { get; set; }
    }
}
