//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace urban_archive.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_VideoArchivesList
    {
        public long videoProjectSeqNo { get; set; }
        public string ProjectIDS { get; set; }
        public string projectName { get; set; }
        public string videoStatus { get; set; }
        public Nullable<System.DateTime> shootingDate { get; set; }
        public string videoCassetteBoxCount { get; set; }
        public string photoBoxCount { get; set; }
    }
}
